### ISSUE TITLE
Regularized Evolution defaults conflicting

### ISSUE THREAD

**Issue by karibbov** [automl/neps#15]
Regularized evolution by default expects `assisted_zero_cost_proxy: Callable` to be assigned since the default value of the `assisted: bool` is `True`. But the default `assisted_zero_cost_proxy: Callable` is `None`. So the regularized evolution can't be run without changing any of the defaults. 

Just changing the default of `assisted` into `False` would solve this. Just want to make sure this was not intended, before I make the change.

**Comment by infomon** [comment]
Yes, you can go ahead with the change and set `assisted` by default to `False`.
