### ISSUE TITLE
Possibly drop GraKel to support `Python>3.7`

### ISSUE THREAD

**Issue by eddiebergman** [automl/neps#2]
I did some cursory glancing at GraKel and it's build systems and it looks like it won't be very actively maintained and it's a bit convoluted with its build systems. I would recommend dropping it as soon as possible or NEPS will be locked for a long while.

I'm not sure how difficult this would be. Could be a hiwi job if you want to create a pure numpy replacement, otherwise maybe just switch to a different graph kernel which doesn't require being built.

I also checked to see if there are any [community forks](https://github.com/ysig/GraKeL/network) which actually fix this issue but not unfortunatly.

I'll keep communication with them at this [PR](https://github.com/ysig/GraKeL/pull/82) and see if I can get maintainer access to switch to an easier and change to a more maintainable build system using github actions.

**Comment by eddiebergman** [comment]
Update:

Seems I got the go ahead to basically modernize it :) Will update the title of the issue to reflect it

**Comment by DaStoll** [comment]
NePS now supports python>3.7
