### ISSUE TITLE
Warning from Pandas while running NePS

### ISSUE THREAD

**Issue by danrgll** [automl/neps#27]
...python3.9/site-packages/pandas/core/dtypes/cast.py:1641: DeprecationWarning: np.find_common_type is deprecated.  Please use `np.result_type` or `np.promote_types`.
See https://numpy.org/devdocs/release/1.25.0-notes.html and the docs for more information.  (Deprecated NumPy 1.25)
  return np.find_common_type(types, [])

Just experience the occurrence when I use a fidelity approach

**Comment by eddiebergman** [comment]
This went away when I installed `pandas>=2.0`, related issue #25
