### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by bastis007** [automl/neps#6]

**Comment by danrgll** [comment]
Hi Bastian,
We've added documentation on most of the capabilities of NePS. We are going to release it in the next few days on our website via the next NePS version update, but you can already find it on the master branch under the docs folder.

**Comment by danrgll** [comment]
Hi Bastian,
We've added documentation on most of the capabilities of NePS. We are going to release it in the next few days on our website via the next NePS version update, but you can already find it on the master branch under the docs folder.
